import type { NextPage } from "next";
import Head from "next/head";
// components
import Form from "../components/Form";
import Resume from "../components/Resume";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Controle Financeiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Resume />
      <Form />
    </div>
  );
};

export default Home;
